#!/usr/bin/env python3
"""Generate the known-answer vectors the device checks its hardware against.

The point is independence: these come from a host library and the public NIST
GCM test set, never from the STM32 HAL, so a passing test on the target proves
the silicon agrees with the specification rather than with itself."""
import textwrap

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

# GCM case 4: the one with AAD and a payload that is not a whole number of blocks.
# radio_devices_docs/wl55_device/testing/host-tests.md
GCM_KEY = bytes.fromhex("feffe9928665731c6d6a8f9467308308")
GCM_IV = bytes.fromhex("cafebabefacedbaddecaf888")
GCM_AAD = bytes.fromhex("feedfacedeadbeeffeedfacedeadbeefabaddad2")
GCM_PT = bytes.fromhex(
    "d9313225f88406e5a55909c5aff5269a86a7a9531534f7da2e4c303d8a318a72"
    "1c3c0c95956809532fcf0e2449a6b525b16aedf5aa0de657ba637b39")
GCM_CT = bytes.fromhex(
    "42831ec2217774244b7221b784d0d49ce3aa212f2c02a4e035c17e2329aca12e"
    "21d514b25466931c7d8f6a5aac84aa051ba30b396a0aac973d58e091")
GCM_TAG = bytes.fromhex("5bc94fbc3221a5db94fae95ae7121a47")

def check_gcm():
    got = AESGCM(GCM_KEY).encrypt(GCM_IV, GCM_PT, GCM_AAD)
    assert got == GCM_CT + GCM_TAG, "GCM vector is wrong"


def carray(name, data):
    body = "\n".join(textwrap.wrap(", ".join("0x%02x" % b for b in data), 88))
    body = textwrap.indent(body, "    ")
    return "static const uint8_t %s[%d] = {\n%s\n};\n" % (name, len(data), body)


# RFC 7748 6.1, copied from the RFC and checked against the library below.
# radio_devices_docs/wl55_device/security/self-tests.md
X_A_PRIV = bytes.fromhex(
    "77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a")
X_A_PUB = bytes.fromhex(
    "8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a")
X_B_PRIV = bytes.fromhex(
    "5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb")
X_B_PUB = bytes.fromhex(
    "de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f")
X_SHARED = bytes.fromhex(
    "4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742")
# u = 0 has order 1: every scalar sends it to zero, and zero must be refused.
X_LOW_ORDER = bytes(32)


def check_x25519():
    from cryptography.hazmat.primitives.asymmetric import x25519
    a = x25519.X25519PrivateKey.from_private_bytes(X_A_PRIV)
    b = x25519.X25519PrivateKey.from_private_bytes(X_B_PRIV)
    assert a.public_key().public_bytes_raw() == X_A_PUB, "RFC 7748 alice public"
    assert b.public_key().public_bytes_raw() == X_B_PUB, "RFC 7748 bob public"
    assert a.exchange(b.public_key()) == X_SHARED, "RFC 7748 shared secret"
    assert b.exchange(a.public_key()) == X_SHARED, "RFC 7748 shared, other way"


def main():
    check_gcm()
    check_x25519()

    lines = [
        "/* Generated by tools/gen_vectors.py - do not edit by hand. */",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        carray("vec_gcm_key", GCM_KEY),
        carray("vec_gcm_iv", GCM_IV),
        carray("vec_gcm_aad", GCM_AAD),
        carray("vec_gcm_pt", GCM_PT),
        carray("vec_gcm_ct", GCM_CT),
        carray("vec_gcm_tag", GCM_TAG),
        carray("vec_x25519_a_priv", X_A_PRIV),
        carray("vec_x25519_a_pub", X_A_PUB),
        carray("vec_x25519_b_priv", X_B_PRIV),
        carray("vec_x25519_b_pub", X_B_PUB),
        carray("vec_x25519_shared", X_SHARED),
        carray("vec_x25519_low_order", X_LOW_ORDER),
    ]
    with open("Core/Inc/crypto_vectors.h", "w") as f:
        f.write("\n".join(lines))
    print("x25519 rfc7748 6.1 shared =", X_SHARED.hex())


if __name__ == "__main__":
    main()
